describe('User workflow test', () => {
  it('should pass all steps', () => {
    // Create accopunt
    cy.visit('http://localhost:8080/')
    cy.contains(/Inscription/).click()
    cy.url().should('include', '/register')
    cy.get('#email').type('fake@email.com')
    cy.get('#email').should('have.value', 'fake@email.com')
    cy.get('#password').clear()
    cy.get('#password').type('@Test123')
    cy.get('#confirm-password').clear()
    cy.get('#confirm-password').type('@Test124')
    cy.get('#nickname').type('UserTest')
    cy.contains(/Enregistrer/).click()
    cy.contains(/Les mots de passe ne correspondent pas./)
    cy.get('#confirm-password').clear()
    cy.get('#confirm-password').type('@Test123')
    cy.contains(/Enregistrer/).click()
    cy.url().should('include', '/profile')

    // Disconnexion
    cy.visit('http://localhost:8080/profile')
    cy.get('#profil-head-avatar').click()
    cy.get('#disconnexion-head').click()
    cy.contains(/Déconnexion réussie/)

    // Connexion
    cy.visit('http://localhost:8080/login')
    cy.get('#email').type('fake')
    cy.get('#password').type('@Test')
    cy.get('#connexion-button').click()
    cy.contains(/email must be a valid email/)
    cy.get('#email').type('@email.com')
    cy.get('#connexion-button').click()
    cy.contains(/Erreur lors de la connexion/)
    cy.get('#password').type('123')
    cy.get('#connexion-button').click()
    cy.contains(/Connexion réussie/)

    // Edit Profile
    cy.visit('http://localhost:8080/profile')
    cy.get('#edit-profile-button').click()
    cy.contains(/Mes informations/)
    cy.get('#edit-profile-button').click()
    cy.contains(/Editer mon profil/)
    cy.get('#edit-profile-cancel').click()
    cy.contains(/Mes informations/)
    cy.get('#edit-profile-button').click()
    cy.contains(/Editer mon profil/)
    cy.get('#firstName').type('User')
    cy.get('#lastName').type('Test')
    cy.get('#city').type('Tlse')
    cy.get('#description').type('Texte de présentation de mon profil')
    cy.get('#edit-profile-save').click()
    cy.contains(/Profil mis à jour avec succès !/)
    cy.contains(/Test/)
    cy.contains(/User/)
    cy.contains(/Tlse/)
    cy.contains(/Texte de présentation de mon profil/)

    // Edit Password
    cy.visit('http://localhost:8080/settings')
    cy.contains(/Mes informations/)
    cy.get('#edit-password-button').click()
    cy.contains(/Editer mon profil/)
    cy.get('#edit-password-cancel').click()
    cy.contains(/Mes informations/)
    cy.get('#edit-password-button').click()
    cy.contains(/Editer mon profil/)
    cy.get('#old-password').type('@Test')
    cy.get('#new-password').type('@Test123')
    cy.get('#confirm-password').type('@Test124')
    cy.get('#edit-password-save').click()
    cy.contains(/Les mots de passe ne correspondent pas./)
    cy.get('#confirm-password').clear()
    cy.get('#confirm-password').type('@Test123')
    cy.get('#edit-password-save').click()
    cy.contains(/Impossible de mettre à jour le mot de passe./)
    cy.get('#old-password').clear()
    cy.get('#old-password').type('@Test123')
    cy.get('#edit-password-save').click()
    cy.contains(
      /Le nouveau mot de passe ne peut pas être le même que l'ancien./
    )
    cy.get('#new-password').clear()
    cy.get('#new-password').type('@Test124')
    cy.get('#confirm-password').clear()
    cy.get('#confirm-password').type('@Test124')
    cy.get('#edit-password-save').click()
    cy.contains(/Mot de passe mis à jour avec succès !/)

    // Delete account
    cy.visit('http://localhost:8080/settings')
    cy.get('#delete-account').click()
    cy.contains(/Êtes-vous sûr de vouloir faire ça ?/)
    cy.get('#delete-account-cancel').click()
    cy.contains(/Mes informations/)
    cy.get('#delete-account').click()
    // cy.get('#password').type('@Test123')
    // cy.get('#delete-account-confirm').click()
    // cy.contains(/Error while deleting the account, please try again later/)
    // cy.get('#delete-account').click()
    // cy.get('#password').type('@Test124')
    // cy.get('#delete-account-confirm').click()
    // cy.contains(
    //   /Compte, blogs et articles supprimés avec succès, même si nous sommes triste de vous voir partir/
    // )
  })
})
